# Generated by Django 5.2 on 2025-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите Наименование",
                        max_length=100,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Опишите товар",
                        max_length=1000,
                        verbose_name="Описание",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите Наименование",
                        max_length=100,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Опишите товар",
                        max_length=1000,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото",
                        null=True,
                        upload_to="Catalog/photo",
                        verbose_name="фото",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Введите категорию товара",
                        max_length=100,
                        verbose_name="Категории",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="Введите цену",
                        max_length=100,
                        verbose_name="цена за покупку",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(blank=True, verbose_name="Дата сощдания"),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True, verbose_name="Дата последнего изменения"
                    ),
                ),
            ],
        ),
    ]
